sudo : required
language: generic
services : 
  - docker

before_install :
  - docker build -t megaraj/react -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true megaraj/react-test npm test

after_success :
  - docker build -t megaraj/client ./client
  - docker build -t megaraj/nginx ./nginx
  - docker build -t megaraj/server ./server
  - docker build -t megaraj/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push megaraj/client 
  - docker push megaraj/nginx
  - docker push megaraj/server
  - docker push megaraj/worker
